os:
  - linux
  - osx
language: cpp
env:
  - NODE_VERSION="0.8"
  - NODE_VERSION="0.10"
  - NODE_VERSION="0.12"
  - NODE_VERSION="4.0"
  - NODE_VERSION="4.1"
  - NODE_VERSION="4.2"
  - NODE_VERSION="5.0"
  - NODE_VERSION="5.1"
  - NODE_VERSION="5.2"
  - NODE_VERSION="5.3"
  - NODE_VERSION="5.4"
  - NODE_VERSION="5.5"
matrix:
  fast_finish: true
before_install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm;
  - source /tmp/.nvm/nvm.sh;
  - nvm install $NODE_VERSION;
  - nvm use --delete-prefix $NODE_VERSION;
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="g++-4.8";
    fi
  - if [ $NODE_VERSION == "0.8" ]; then
      npm install -g npm@2;
    fi
install:
  - npm install
script:
  - npm test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
