os:
  - linux
  - osx
language: cpp
env:
  - NODE_VERSION="6"
  - NODE_VERSION="8"
  - NODE_VERSION="10"
matrix:
  fast_finish: true
before_install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm;
  - source /tmp/.nvm/nvm.sh;
  - nvm install $NODE_VERSION;
  - nvm use --delete-prefix $NODE_VERSION;
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="g++-4.8";
    fi
install:
  - npm install
script:
  - npm test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
